### ISSUE TITLE
Handle connection establishment in-progress: enhance all buttons in all samples

### ISSUE THREAD

**Issue by wlyeow** [SolaceSamples/solace-samples-javascript#26]
A connection can take a long time to fail because of the defaults:
```
Class solace.SessionProperties 
Number | connectRetries        = 20
Number | connectRetriesPerHost = 0
Number | connectTimeoutInMsecs = 8000
```
Example:
> [10:46:50] Connecting to Solace message router using url: wss://random-service.messaging.solace.cloud:random-port
> [10:46:50] Client username: solace-cloud-client
> [10:46:50] Solace message router VPN name: msgvpn-random
> [10:48:18] Connection failed to the message router: Unauthorized - check correct parameter values and connectivity!

Until the following line appears, we shouldn't click on anything else:
> [10:41:08] === Successfully connected and ready to publish messages. ===

Otherwise, we get confusing messages, especially for first-time users. The following examples are for [TopicPublisher.html](../blob/9306541/src/basic-samples/TopicPublisher/TopicPublisher.html).

Example 1: Clicking the "connect" button again tells you you're already connected when you're actually NOT:
> [10:40:51] Connecting to Solace message router using url: wss://random-service.messaging.solace.cloud:random-port
> [10:40:51] Client username: solace-cloud-client
> [10:40:51] Solace message router VPN name: msgvpn-random
> [10:40:56] Already connected and ready to publish messages.

Example 2: Clicking the "publish" button before actually connected gives "state WaitingForInterconnectTimeout" which can be confusing:
> [11:04:43] Connecting to Solace message router using url: wss://random-service.messaging.solace.cloud:random-port
> [11:04:43] Client username: solace-cloud-client
> [11:04:43] Solace message router VPN name: msgvpn-random
> [11:04:45] Publishing message "Sample Message" to topic "tutorial/topic"...
> [11:04:45] OperationError: Cannot perform operation SEND while in state WaitingForInterconnectTimeout

Example 3: Clicking "Connect" again after a failed connection actually requires the user to click "Disconnect", otherwise you'll get this:
> [10:46:50] Connecting to Solace message router using url: wss://random-service.messaging.solace.cloud:random-port
> [10:46:50] Client username: solace-cloud-client
> [10:46:50] Solace message router VPN name: msgvpn-random
> [10:48:18] Connection failed to the message router: Unauthorized - check correct parameter values and connectivity!
> [11:03:36] Already connected and ready to publish messages.

Of course, the defaults can be adjusted for responsiveness but I think a better way is to have the buttons be greyed out appropriately in the samples. This can also help illustrate event handling in the API.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
