### ISSUE TITLE
Web UI is not given as an option to create a queue

### ISSUE THREAD

**Issue by thrillstone** [SolaceSamples/solace-samples-javascript#29]
In the persistence with queues sample, there is a prerequisite section that mentions you must create a queue and that you can do so using SolAdmin or SEMP. It fails to mention that you could also do so using the Web UI. The Web UI should be one of the options.

It would also make sense if the section linked to the instructions to create a queue, although I'm not sure if we have such a sample online.

**Comment by aaron-613** [comment]
Hi @Mrc0113 , just tidying up old issues.  Noticed there were still some references to SolAdmin, so I created https://github.com/SolaceDev/solace-dev-tutorials/pull/131

Once that's merged, let's close this Issue.
