### ISSUE TITLE
Sample to demonstrate sending requests to Solace Cache

### ISSUE THREAD

**Issue by solace-dmckay** [SolaceSamples/solace-samples-javascript#49]
It would be useful to have a sample that demonstrates how to use the JS API to send requests to Solace Cache.

**Comment by aaron-613** [comment]
Old samples added to branch `issue-49-add-solcache-sample` as part of https://github.com/SolaceSamples/solace-samples-javascript/pull/54

**Comment by Mrc0113** [comment]
Closing as Stale
